# -*- coding: utf-8 -*-
"""tugas3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9WRXzLwiLaJ1CimKMEQHxe-BYyDGu1D
"""

# 1. Deklarasi Variabel dan Tipe Data
nama_tugas = "Python AI B10"  # string
versi_python = 3               # integer
skor_akurasi = 95.5            # float
sedang_belajar = True          # boolean
bahasa_pemrograman = ["Python", "JavaScript", "C++", "Java", "PHP"]  # list

# 2. Manipulasi String
print("--- Manipulasi String ---")
teks_tambahan = " Selesai"
print("Gabungan string:", nama_tugas + teks_tambahan)
print("Panjang string:", len(nama_tugas))
print("Huruf besar:", nama_tugas.upper())
print("Huruf kecil:", nama_tugas.lower())
print()

# 3. Operasi Matematika Sederhana
print("--- Operasi Matematika ---")
a = 20
b = 6
print("Penjumlahan (a + b):", a + b)
print("Pengurangan (a - b):", a - b)
print("Perkalian (a * b):", a * b)
print("Pembagian (a / b):", a / b)
print("Pembagian Bulat (a // b):", a // b)
print("Sisa Bagi/Modulus (a % b):", a % b)
print()

# 4. List dan Akses Elemen
print("--- List dan Akses Elemen ---")
print("List awal:", bahasa_pemrograman)
print("Elemen ke-2:", bahasa_pemrograman[1])

bahasa_pemrograman.append("Ruby")
print("Setelah append:", bahasa_pemrograman)

bahasa_pemrograman.remove("PHP")
print("Setelah remove:", bahasa_pemrograman)
print()

# 5. Penggunaan Input dari User
print("--- Input User ---")
nama_user = input("Masukkan nama Anda: ")
umur_user = input("Masukkan umur Anda: ")
print(f"Halo, nama saya {nama_user} dan umur saya {umur_user} tahun.")