# -*- coding: utf-8 -*-
"""tugas5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGkE8yM3aJOcdey18HGGKjQ97bs9M8Dl
"""

def greet(nama: str) -> str:
    return f"Halo, {nama}!"

def tambah(a: float, b: float = 0.0) -> float:
    return a + b

def rata_rata(angka: list[float]) -> float:
    if not angka:
        return 0.0
    return round(sum(angka) / len(angka), 2)

class Student:
    def __init__(self, nama: str, nim: str, nilai: list[float] = None):
        self.nama = nama
        self.nim = nim
        self.nilai = nilai if nilai is not None else []

    def tambah_nilai(self, skor: float):
        self.nilai.append(skor)

    def rata_nilai(self) -> float:
        return rata_rata(self.nilai)

    def status(self, threshold: float = 70.0) -> str:
        if self.rata_nilai() >= threshold:
            return "LULUS"
        return "TIDAK LULUS"

    def __str__(self):
        return f"Student(nama='{self.nama}', nim='{self.nim}', rata={self.rata_nilai()}, status={self.status()})"

if __name__ == "__main__":
    print("=== FUNCTIONS ===")
    print(greet("Dian"))
    print(f"tambah(5, 7): {tambah(5, 7)}")
    print(f"tambah(10): {tambah(10)}")
    print(f"rata_rata([80, 90, 100]): {rata_rata([80, 90, 100])}")
    print(f"rata_rata([]): {rata_rata([])}")

    print("\n=== CLASS STUDENT ===")
    student1 = Student(nama="Dian Purbo Wicaksono", nim="G.211.23.0004")
    student1.tambah_nilai(85.5)
    student1.tambah_nilai(92.0)
    student1.tambah_nilai(88.0)

    student2 = Student(nama="Indra Echo Gamink", nim="G.211.23.0067")
    student2.tambah_nilai(60.0)
    student2.tambah_nilai(65.5)

    print(student1)
    print(f"Rata-rata: {student1.rata_nilai()} | Status: {student1.status()}")

    print(student2)
    print(f"Rata-rata: {student2.rata_nilai()} | Status: {student2.status()}")