# -*- coding: utf-8 -*-
"""tugas4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2AtcBu3vbyUKy93ERnbk6WVclHu4Tyd
"""

# List – akses & manipulasi
my_list = [10, "Dian Purbo Wicaksono", 3.14, True, "Python", 42]
print(f"List awal: {my_list}")
print(f"Elemen pertama: {my_list[0]}, terakhir: {my_list[-1]}")
print(f"Slicing [1:5:2]: {my_list[1:5:2]}")

my_list.append("Baru")
my_list.insert(2, "Sisip")
my_list.extend([100, 200])
print(f"Setelah append, insert, extend: {my_list}")

my_list.pop()
my_list.remove("Python")
print(f"Setelah pop dan remove: {my_list}\n")

# Tuple – immutability & unpacking
my_tuple = (1, 2, 3, 4, 5, 6)
print(f"Tuple: {my_tuple}")
print(f"Panjang tuple: {len(my_tuple)}")
print(f"Akses indeks ke-2: {my_tuple[2]}")

a, b, *rest = my_tuple
print(f"Unpacking: a={a}, b={b}, rest={rest}\n")

# Set – keunikan & operasi himpunan
set_A = {1, 2, 2, 3, 4, 5}  # Duplikat angka 2 otomatis hilang
set_B = {4, 5, 6, 7, 7, 8}  # Duplikat angka 7 otomatis hilang
print(f"Set A: {set_A}")
print(f"Set B: {set_B}")

print(f"Union (|): {set_A | set_B}")
print(f"Intersection (&): {set_A & set_B}")
print(f"Difference A - B (-): {set_A - set_B}")
print(f"Symmetric Difference (^): {set_A ^ set_B}\n")

# Dictionary – key/value dasar
mahasiswa = {"nama": "Dian Purbo Wicaksono", "nim": "G.211.23.0004", "angkatan": 2023, "kota": "Semarang"}
print(f"Dict awal: {mahasiswa}")

mahasiswa["jurusan"] = "Teknik Informatika"  # Tambah key baru
mahasiswa["kota"] = "Semarang"         # Ubah nilai key
del mahasiswa["angkatan"]             # Hapus key
print(f"Dict setelah operasi: {mahasiswa}")

print(f"Keys: {mahasiswa.keys()}")
print(f"Values: {mahasiswa.values()}")
print(f"Items: {mahasiswa.items()}")

print("Iterasi key: value:")
for k, v in mahasiswa.items():
    print(f"- {k}: {v}")
print()

# Nested structures
daftar_buku = [
    {"judul": "Buku 67", "penulis": "MrBeast", "tahun": 2010},
    {"judul": "Buku Kesuksesan berawal dari orang tua kaya", "penulis": "Erpan1140", "tahun": 2020},
    {"judul": "Buku Usaha Menghianati Hasil", "penulis": "Don Vito", "tahun": 2018},
    {"judul": "Buku Lore Runeterra", "penulis": "Riot", "tahun": 2022}
]

print("Daftar Judul Buku:")
for buku in daftar_buku:
    print(f"- {buku['judul']}")

buku_baru = [buku for buku in daftar_buku if buku['tahun'] >= 2020]
print(f"Filter buku terbit >= 2020: {buku_baru}\n")

# Comprehension & utilitas
angka_1_20 = range(1, 21)
list_genap = [x for x in angka_1_20 if x % 2 == 0]
list_kuadrat = [x**2 for x in angka_1_20]
print(f"List genap: {list_genap}")
print(f"List kuadrat: {list_kuadrat}")

dict_genap_ganjil = {x: "genap" if x % 2 == 0 else "ganjil" for x in range(1, 11)}
print(f"Dict genap/ganjil (1-10): {dict_genap_ganjil}")

kalimat = "Halo Sir V"
set_huruf = {huruf.lower() for huruf in kalimat if huruf.isalpha()}
print(f"Set huruf unik dari kalimat: {set_huruf}\n")

# Keanggotaan & pencarian sederhana
item_cari = 3
print(f"Apakah {item_cari} ada di set_A? {'Ya' if item_cari in set_A else 'Tidak'}")

list_cari = [10, 20, 30, 40]
target = 30
if target in list_cari:
    posisi = list_cari.index(target)
    print(f"Item {target} ditemukan pada indeks ke-{posisi} di list_cari")
else:
    print(f"Item {target} tidak ditemukan di list_cari")