# -*- coding: utf-8 -*-
"""tugas6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omBTWrHrVBDHTFXmECEjrg0nn8l0Hp-v
"""

import os
import numpy as np
import pandas as pd

# Setup Seed
np.random.seed(42)

class GradeBook:
    def __init__(self, df: pd.DataFrame):
        self.df = df

    def average(self) -> float:
        return float(self.df['nilai'].mean())

    def pass_rate(self, threshold: float = 70.0) -> float:
        total = len(self.df)
        if total == 0:
            return 0.0
        lulus = len(self.df[self.df['nilai'] >= threshold])
        return (lulus / total) * 100

    def save_summary(self, path: str):
        with open(path, 'a') as f:
            f.write("\n=== SUMMARY DARI OOP GRADEBOOK ===\n")
            f.write(f"Total Data DataFrame : {len(self.df)}\n")
            f.write(f"Rata-rata Nilai      : {self.average():.2f}\n")
            f.write(f"Persentase Lulus     : {self.pass_rate():.2f}%\n")

    def __str__(self):
        return f"GradeBook(Jumlah Data: {len(self.df)}, Rata-rata: {self.average():.2f})"


if __name__ == "__main__":
    # === NUMPY ===
    print("=== NUMPY ===")
    nilai_ujian = np.random.randint(50, 100, size=12)

    mean_val = np.mean(nilai_ujian)
    median_val = np.median(nilai_ujian)
    std_val = np.std(nilai_ujian)
    min_val = np.min(nilai_ujian)
    max_val = np.max(nilai_ujian)

    print(f"Array Nilai Ujian : {nilai_ujian}")
    print(f"Rata-rata         : {mean_val:.2f}")
    print(f"Median            : {median_val:.2f}")
    print(f"Standar Deviasi   : {std_val:.2f}")
    print(f"Nilai Min         : {min_val}")
    print(f"Nilai Max         : {max_val}\n")

    # === PANDAS ===
    print("=== PANDAS ===")
    data = {
        "nama": ["Dian Purbo Wicaksono", "Indra", "Fuad", "Dimas", "Kai Cenat", "Tuan Buas"],
        "nim": ["G.211.23.0004", "G.211.23.0005", "G.211.23.0006", "G.211.23.0007", "G.211.23.0008", "G.211.23.0009"],
        "nilai": nilai_ujian[:6]
    }
    df = pd.DataFrame(data)
    df["status"] = np.where(df["nilai"] >= 70, "LULUS", "TIDAK LULUS")
    print(df.head())
    print()

    # === FILE I/O ===
    file_path = "ringkasan_tugas6.txt"
    with open(file_path, 'w') as f:
        f.write("=== RINGKASAN STATISTIK NUMPY ===\n")
        f.write(f"Rata-rata       : {mean_val:.2f}\n")
        f.write(f"Median          : {median_val:.2f}\n")
        f.write(f"Standar Deviasi : {std_val:.2f}\n")
        f.write(f"Nilai Min       : {min_val}\n")
        f.write(f"Nilai Max       : {max_val}\n\n")

        f.write("=== RINGKASAN DATAFRAME ===\n")
        f.write(f"Jumlah Baris    : {len(df)}\n")
        f.write(f"Jumlah Lulus    : {len(df[df['status'] == 'LULUS'])}\n")
        f.write(f"Jumlah Tdk Lulus: {len(df[df['status'] == 'TIDAK LULUS'])}\n")

    # === OOP: GRADEBOOK ===
    print("=== OOP: GRADEBOOK ===")
    buku_nilai = GradeBook(df)
    print(buku_nilai)
    print(f"Average   : {buku_nilai.average():.2f}")
    print(f"Pass Rate : {buku_nilai.pass_rate():.2f}%")

    buku_nilai.save_summary(file_path)
    print(f"\n[Info untuk Sir Dian Purbo Wicaksono]: File '{file_path}' berhasil dibuat dan disimpan.")